sudo: required
services:
    - docker
before_install:
    - docker build -t chiran/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true chiran/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "docker-aws"
    env: "DockerAws-env"
    bucket_name: "elasticbeanstalk-us-east-2-200045631441"
    bucket_path: "docker"
    on:
        branch: master
    accerss_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"