sudo: required
services:
    - docker
before_install:
    - docker build -t chiran/docker-react -f Dockerfile.dev .

script:
    - docker run chiran/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: ""
    app: "docker-aws"
    env: ""
    bucket_name: ""
    bucket_path: ""
    on:
        branch: master
    accerss_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"